### ISSUE TITLE
只要把你的这个js文件替换掉原来的就可以使用了吗？

### ISSUE THREAD

**Issue by weichencoder** [yujiangshui/my-ShadowsocksX-gfwlist#1]
另外，如果我想让苹果所有服务都走代理。该怎么写规则呢？苹果的ip是17.xxx.xxx.xxx

**Comment by yujiangshui** [comment]
这个只是我存放一些自定义翻墙配置的地方，这些域名是我平时访问遇到的比较慢的域名，让他直接走代理。

你的这个需求我不太清楚，如果是为了 app 下载等，不需要这样做，目前苹果在国内的网速还是挺好的。
